/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GridTest{
	@Test
	void getLeft_test(){
		grid testGrid = new grid();
		cell testCell1 = new cell();
		cell testCell2 = new cell();
		testCell1.x = 1;
		testCell1.y = 2;
		testCell2.hasShip = true;
		testGrid.cells[0][2] = testCell2;
		cell newCell = testGrid.getLeft(testCell1);
		assertEquals(0, newCell.x);
	}
	@Test
	void getRight_test(){
		grid testGrid = new grid();
		cell testCell1 = new cell();
		cell testCell2 = new cell();
		testCell1.x = 8;
		testCell1.y = 2;
		testCell2.x = 9;
		testCell2.y = 2;
		testCell2.hasShip = true;
		testGrid.cells[9][2] = testCell2;
		cell newCell = testGrid.getRight(testCell1);
		assertEquals(9, newCell.x);
	}
	@Test
	void getUp_test(){
		grid testGrid = new grid();
		cell testCell1 = new cell();
		cell testCell2 = new cell();
		testCell1.x = 9999;
		testCell1.y = -41;
		testCell2.x = 123;
		testCell2.y = 33;
		testCell2.hasShip = true;
		testGrid.cells[9][2] = testCell2;
		cell newCell = testGrid.getRight(testCell1);
		if (newCell == null) {
			System.out.println("Success: Cell is null");
		}
	}
	void updatesunk_test() {

	}


}

