/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.InputMismatchException;
import java.util.Objects;
import java.util.Scanner;
import java.util.concurrent.ThreadLocalRandom;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;
import org.apache.commons.csv.CSVRecord;

public class App {

	public static void main(String[] args) {
		grid Grid = new grid();
		int[] field = new int[100];
		field[3] = 2;
		field[4] = 2;
		Grid.cells[0][2].hasShip = true;
		Grid.cells[0][3].hasShip = true;
		Grid.cells[0][4].hasShip = true;
		int[] g = Grid.hunt_target_shoot(field);
		System.out.print(g[0]);
		System.out.print(g[1]);
		System.out.print(field[0]);
		System.out.print(field[1]);
		System.out.print(field[2]);
		System.out.print(field[3]);
		System.out.print(field[4]);
		System.out.print(field[5]);
		//System.out.print(field[6]);
	}
		/*
		GameEngine ge = new GameEngine();

		Scanner scanner = new Scanner(System.in);
		System.out.println("Which game mode do you want to play?" );
		System.out.println("Default (d)");
		System.out.println("unfair Game (u)");
		String input = scanner.nextLine();
		//switch statement for future game modes
		switch (input) {
			case "d" -> ge.standardGame();
			case "u" -> ge.unfairGame();
			case "upupdowndownleftrightleftrightBA"->{
				ge.victory();
			}
			default -> {
				System.out.println("Looks like you don't want to play. (╥︵╥) ");
				System.out.println("cya next time.");
			}
		}
	}
	*/
}

